# [NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html#numpy-the-absolute-basics-for-beginners)


![alt text](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXXTF81F5FPmbpq54WWuGDXuFt4hUPlYoLyOWqbfjbqQ&s=10)


In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
a.shape

(2, 3)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a[0]

np.int64(1)

In [ ]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [ ]:
a[:3]

array([10,  2,  3])

In [ ]:
b = a[3:]
b

array([4, 5, 6])

In [ ]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[1, 3]

np.int64(8)

# Array Attributes


In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a.ndim

2

In [ ]:
a.shape

(3, 4)

In [ ]:
len(a.shape) == a.ndim  # len() counts how many values are in the tuple.

True

In [ ]:
a.size

12

In [ ]:
import math

In [ ]:
a.size == math.prod(a.shape)

True

In [ ]:
a.dtype

dtype('int64')

# How to create a basic array


In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.empty(2)  # The reason to use empty over zeros (or something similar) is speed

array([1., 1.])

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
np.arange(2, 9, 2)  # arange(start, end, step)

array([2, 4, 6, 8])

In [ ]:
np.linspace(
    0, 10, num=5
)  # np.linspace() to create an array with values that are spaced linearly in a specified interval

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

# Adding, removing, and sorting elements


In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [ ]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [ ]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
array_example = np.array(
    [
        [[0, 1, 2, 3], [4, 5, 6, 7]],
        [[0, 1, 2, 3], [4, 5, 6, 7]],
        [[0, 1, 2, 3], [4, 5, 6, 7]],
    ]
)

In [ ]:
array_example.ndim

3

In [ ]:
array_example.size

24

In [ ]:
array_example.shape

(3, 2, 4)

In [ ]:
a = np.arange(6)

In [ ]:
print(a)

[0 1 2 3 4 5]


In [ ]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
np.reshape(a, (1, 6), order="C")

array([[0, 1, 2, 3, 4, 5]])

# How to convert a 1D array into a 2D array


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
a2 = a[np.newaxis, :]

In [ ]:
a2.shape

(1, 6)

In [ ]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [ ]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [ ]:
a.shape

(6,)

In [ ]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [ ]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# Indexing and slicing


In [ ]:
data = np.array([1, 2, 3])
data[1]

np.int64(2)

In [ ]:
data[0:2]

array([1, 2])

In [ ]:
data[1:]

array([2, 3])

In [ ]:
data[-2:]

array([2, 3])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
print(a[a < 5])

[1 2 3 4]


In [ ]:
five_up = a >= 5
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [ ]:
divisible_by_2 = a[a % 2 == 0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [ ]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [ ]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [ ]:
list_of_coordinates = list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [ ]:
print(a[b])

[1 2 3 4]


In [ ]:
not_there = np.nonzero(
    a == 42
)  # If the element you’re looking for doesn’t exist in the array, then the returned array of indices will be empty.
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


# How to create an array from existing data


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
arr1 = a[3:8]

In [ ]:
arr1

array([4, 5, 6, 7, 8])

In [ ]:
a1 = np.array([[1, 1], [2, 2]])

In [ ]:
a2 = np.array([[3, 3], [4, 4]])

In [ ]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [ ]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [ ]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [ ]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b2 = a.copy()

# Basic array operations


In [ ]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

In [ ]:
data + ones

array([2, 3])

In [ ]:
data - ones

array([0, 1])

In [ ]:
data * ones

array([1, 2])

In [ ]:
data / data

array([1., 1.])

In [ ]:
a = np.array([1, 2, 3, 4])

a.sum()

np.int64(10)

In [ ]:
b = np.array([[1, 1], [2, 2]])

In [ ]:
np.sum(b, axis=0)

array([3, 3])

In [ ]:
b.sum(axis=1)

array([2, 4])

# **[Broadcasting](https://numpy.org/doc/stable/user/absolute_beginners.html#broadcasting)**

### <span style="color: purple;">Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. The dimensions of your array must be compatible, for example, when the dimensions of both arrays are equal or when one of them is 1.

</span>


In [ ]:
data = np.array([1.0, 2.0])

In [ ]:
data * 1.6

array([1.6, 3.2])

# **More useful array operations**


In [ ]:
data = np.array([1, 2, 3])

In [ ]:
data.max()

np.int64(3)

In [ ]:
max(data)

np.int64(3)

In [ ]:
np.max(data)

np.int64(3)

In [ ]:
data.min()

np.int64(1)

In [ ]:
data.sum()

np.int64(6)

In [ ]:
a = np.array(
    [
        [0.45053314, 0.17296777, 0.34376245, 0.5510652],
        [0.54627315, 0.05093587, 0.40067661, 0.55645993],
        [0.12697628, 0.82485143, 0.26590556, 0.56917101],
    ]
)

In [ ]:
a.sum()

np.float64(4.8595784)

In [ ]:
a.min()

np.float64(0.05093587)

In [ ]:
a.min(axis=0)  # minimum value within each column by specifying axis=0.

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [ ]:
a.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [ ]:
a.max(axis=0)

array([0.54627315, 0.82485143, 0.40067661, 0.56917101])

In [ ]:
np.max(a, axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

# [Creating matrices](https://numpy.org/doc/stable/user/absolute_beginners.html#creating-matrices)


In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data[0, 1]

np.int64(2)

In [ ]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [ ]:
data[0:2, 0]

array([1, 3])

In [ ]:
data.max()

np.int64(6)

In [ ]:
data.min()

np.int64(1)

In [ ]:
np.sum(data, axis=1)

array([ 3,  7, 11])

In [ ]:
sum(data)

array([ 9, 12])

In [ ]:
data.sum(axis=1)

array([ 3,  7, 11])

In [ ]:
data.sum(axis=0)

array([ 9, 12])

In [ ]:
data.sum()

np.int64(21)

In [ ]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data
data.max(axis=0)

array([5, 6])

In [ ]:
data.max(axis=1)

array([2, 5, 6])

In [ ]:
np.max(data, axis=1)

array([2, 5, 6])

In [ ]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
(
    data + ones
)  # add and multiply them using arithmetic operators if you have two matrices that are the same size.

array([[2, 3],
       [4, 5]])

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1], [1], [1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
np.ones(3)
np.zeros(3)
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3)

array([0.86071771, 0.91752644, 0.9756006 ])

In [ ]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
rng.random((3, 2))

array([[0.7155334 , 0.5094196 ],
       [0.95361057, 0.22375721],
       [0.82983342, 0.97019637]])

# Generating random numbers


In [ ]:
rng.integers(5, size=(2, 4))

array([[0, 3, 2, 3],
       [1, 3, 4, 3]])

In [ ]:
rng.integers(
    5, size=(2, 4), endpoint=True
)  #  endpoint=True to make the high number inclusive.

array([[0, 5, 1, 4],
       [2, 4, 4, 3]])

In [ ]:
rng.integers(
    low=0, high=5, size=(2, 4), endpoint=True
)  #  endpoint=True to make the high number inclusive.

array([[4, 5, 0, 5],
       [5, 1, 1, 0]])

# [How to get unique items and counts](https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-get-unique-items-and-counts)


In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [ ]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


**When np.unique(a, return_index=True)** is called, the function **returns a tuple of two NumPy arrays:**

An array containing the sorted unique values of the input array **a** (which is flattened by default if not 1-D or if axis is None).

An array containing the indices in the original (flattened) input array **a** that correspond to the first occurrence of each unique value in the first output array.


In [ ]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [ ]:
indices_list

array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14])

In [ ]:
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

<h5> You can pass the return_counts argument in np.unique() along with your array to get the frequency count of unique values in a NumPy array.</h5>


In [ ]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [ ]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [ ]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
np.unique(a_2d)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
unique_col = np.unique(a_2d, axis=1)

In [ ]:
unique_col

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [ ]:
unique_rows, indices, occurrence_count = np.unique(
    a_2d, axis=0, return_counts=True, return_index=True
)

In [ ]:
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
indices

array([0, 1, 2])

In [ ]:
occurrence_count

array([2, 1, 1])

# [Transposing and reshaping a matrix](https://numpy.org/doc/stable/user/absolute_beginners.html#transposing-and-reshaping-a-matrix)


In [ ]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

# How to reverse an array


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
reversed_arr = np.flip(arr)

In [ ]:
print("Reversed Array: ", reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


#### Reversing a 2D array


In [ ]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [ ]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
reversed_arr_columns

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [ ]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [ ]:
arr_2d[:, 1] = np.flip(arr_2d[:, 1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


# Reshaping and flattening multidimensional arrays


In [ ]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
x.flatten()  # When you use flatten, changes to your new array won’t change the parent array.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(a1)  # New array

[99  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
a2 = (
    x.ravel()
)  # But when you use ravel, the changes you make to the new array will affect the parent array.
a2[0] = 98
print(x)  # Original array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(a2)  # New Array

[98  2  3  4  5  6  7  8  9 10 11 12]


# [How to access the docstring for more information](https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-access-the-docstring-for-more-information)


In [ ]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
a?

In [ ]:
def double(a):
    """Return a * 2"""
    return a * 2

In [ ]:
double?

##### Using a double question mark (??) allows you to access the source code.


In [ ]:
double??

In [ ]:
len?

<h5>Have the same output because they were compiled in a programming language other than Python.</h5>


In [ ]:
len??

# Working with mathematical formulas


![np_MSE_formula.png](attachment:63e4e6a7-ebbf-4a53-909c-70efcd8e987a.png)


![np_MSE_implementation.png](attachment:3f2b8990-6c34-4059-bce9-4b0ab9c16745.png)


![np_mse_viz1.png](attachment:c98a1a43-70de-475e-8752-c0cef6cd1e06.png)


In [ ]:
predictions = np.array([[1], [1], [1]])
labels = np.array([[1], [2], [3]])

In [ ]:
error = (1 / 3) * np.sum(np.square(predictions - labels))

In [ ]:
error

np.float64(1.6666666666666665)

# [How to save and load NumPy objects](https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-save-and-load-numpy-objects)


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
np.save("filename", a)

In [ ]:
b = np.load("filename.npy")

In [ ]:
b

array([1, 2, 3, 4, 5, 6])

In [ ]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

<h5>You can easily save it as a .csv file with the name “new_file.csv” like this:</h5>


In [ ]:
np.savetxt("new_file.csv", csv_arr)

<h5>You can quickly and easily load your saved text file using loadtxt():</h5>


In [ ]:
np.loadtxt("new_file.csv")

array([1., 2., 3., 4., 5., 6., 7., 8.])

# Importing and exporting a CSV


In [ ]:
import pandas as pd

In [ ]:
a = np.array(
    [
        [-2.58289208, 0.43014843, -1.24082018, 1.59572603],
        [0.99027828, 1.17150989, 0.94125714, -0.14692469],
        [0.76989341, 0.81299683, -0.95068423, 0.11769564],
        [0.20484034, 0.34784527, 1.96979195, 0.51992837],
    ]
)

In [ ]:
df = pd.DataFrame(a)
print(df)

          0         1         2         3
0 -2.582892  0.430148 -1.240820  1.595726
1  0.990278  1.171510  0.941257 -0.146925
2  0.769893  0.812997 -0.950684  0.117696
3  0.204840  0.347845  1.969792  0.519928


In [ ]:
data = {"calories": [420, 380, 390], "duration": [50, 40, 45]}

# Load data into a DataFrame object with custom named indexes
df = pd.DataFrame(data, index=["day1", "day2", "day3"])

df

,calories,duration
day1,420,50
day2,380,40
day3,390,45
